### ISSUE TITLE
Redesign website

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq-website#35]
The https://bisq.network site currently has a lot of baggage that has accumulated over the years, and with the launch of the DAO now is a good time to redesign and (radically) simplify the site.

----

UPDATE 2017.12.12: @csacher, @ripcurlx and @cbeams met to kick this off as a project. See comments below for further details.

**Comment by philippnagel** [comment]
I am happy to help. Would love to hear about your ideas!

**Comment by changalberto** [comment]
Happy to help as well

**Comment by cbeams** [comment]
A few quick tasks from our call today with @csacher, @ripcurlx and @cbeams:

 - [ ] Begin working on messaging / content / information design in this GDoc https://docs.google.com/document/d/1l-L9ghjJeNoDShVJ1fFox5GMPaYk2EdyEqVt42aoZvQ/edit?usp=sharing
 - [ ] @ripcurlx to set up and share access to Invision Moodboard (filling it with ideas, inspirations)
 - [ ] @cbeams to upload 5+ inspiration / screenshots etc
 - [ ] @ripcurlx to upload 5+ inspiration / screenshots etc
 - [ ] @csacher to upload 5+ inspiration / screenshots etc
 - [ ] @cbeams to reaches out to HTML5 devs and designers in his network
 - [ ] This group (and anyone else who wants to join) to meet again this time next week, see https://bisq.network/calendar for details.

See complete call notes at https://docs.google.com/document/d/1NtFsSGjm60cqF5XpTKNIzjzbNzpw_yo1t7Pj6PsnV_0/edit

**Comment by ripcurlx** [comment]
moodboard: https://projects.invisionapp.com/boards/Z53GGJM6V8K3F/

**Comment by cbeams** [comment]
This effort is on hold for the moment while the dust settles around some other higher priority issues that cropped up in December, e.g. fee reimbursements, lots of arbitration issues, network stability problems, etc.

**Comment by tr37ion** [comment]
Sounds interesting. I can help if I find the time to contribute.

**Comment by cbeams** [comment]
To those who have offered to help, thank you. Please include a few links to prior public work and say something about your skills so that we know who we can ping for what in the future.

**Comment by changalberto** [comment]
I am mostly a web/front-end developer working in the creative and advertising industry. But because we deal with a variety of clients, ranging all sorts of industry, from makeup brands to medical, I get the opportunity to improve and add new skillsets into my toolbelt.

Most recently, I've been working with React and Angular in Redux, as well as working with Rest API and GraphQL services...

To sum it all up... I can basically make full websites/mobiles independently if needed. I can work all the way from UX/Creative to FullStack... And today I'm trying to learn Blockchain development.

Here's my not so recent "portfolio" if you will (I haven't updated this in over a year...): [http://changalberto.com/](http://changalberto.com/)
 
And feel feel to reach out to me on Slack if you have any questions. My handle is changalberto in the  Bisq Slack

**Comment by cbeams** [comment]
Nice, thanks. Note (to all) that the Bisq website will likely remain extremely simple, even simpler than it is now, and will continue to be a statically generated site using Jekyll and hosted on Netlify. Experience with Jekyll and AsciiDoc are therefore important. Strong HTML5 skills are a must. Work with Bootstrap and similar CSS frameworks required. Mostly we'll be looking for people to help us implement something simple, clean and fast. Note that I'm just talking about frontend development here. Layout and visual design skills can be provided someone else. I will likely do the information architecture myself, i.e. the structure of the website, what information goes where, main navigation, etc.

**Comment by m52go** [comment]
I think it's safe to say this is now complete ;)
